[package]
authors = ["Filip Szczepański <jazz2rulez@gmail.com>"]
name = "ngaro-rs"
version = "0.0.2"

[dependencies]
byteorder = "1.2.1"
docopt = "0.8.3"
termion = "1.5.1"
serde = "1.0"
serde_derive = "1.0"
